-- Q-Ride foundation. Financial entries are append-only; authoritative state transitions
-- happen through trusted RPCs/workers, never from browser updates.
create extension if not exists pgcrypto;
create type public.qr_role as enum ('super_admin','operations_admin','finance_admin','support_agent','driver','customer','corporate_admin','corporate_member');
create type public.qr_ride_status as enum ('draft','quoted','requested','assigned','driver_arrived','in_progress','completed','cancelled','payment_failed');
create type public.qr_wallet_owner as enum ('driver','customer_reward','platform');
create type public.qr_ledger_kind as enum ('ride_credit','commission_debit','payment_capture','refund','withdrawal','bonus','reward_credit','adjustment');

create table public.qr_profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null, phone text unique, role qr_role not null default 'customer', created_at timestamptz not null default now());
create table public.qr_cities (id uuid primary key default gen_random_uuid(), country_code char(2) not null, name text not null, currency char(3) not null default 'NGN', timezone text not null, active boolean not null default true, unique(country_code,name));
create table public.qr_ride_categories (id uuid primary key default gen_random_uuid(), city_id uuid references public.qr_cities(id), code text not null, name text not null, base_fare_minor bigint not null check(base_fare_minor>=0), minimum_fare_minor bigint not null check(minimum_fare_minor>=0), per_km_minor bigint not null check(per_km_minor>=0), per_minute_minor bigint not null check(per_minute_minor>=0), active boolean not null default true, unique(city_id,code));
create table public.qr_drivers (profile_id uuid primary key references public.qr_profiles(id), status text not null check(status in ('pending','under_review','approved','active','suspended','rejected','deactivated')), rating numeric(3,2), verification_state jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.qr_vehicles (id uuid primary key default gen_random_uuid(), driver_id uuid not null references public.qr_drivers(profile_id), category_id uuid references public.qr_ride_categories(id), plate_number text not null, make text not null, model text not null, active boolean not null default true, unique(plate_number));
create table public.qr_rides (id uuid primary key default gen_random_uuid(), public_id text not null unique default encode(gen_random_bytes(9),'hex'), customer_id uuid not null references public.qr_profiles(id), driver_id uuid references public.qr_drivers(profile_id), vehicle_id uuid references public.qr_vehicles(id), city_id uuid not null references public.qr_cities(id), category_id uuid not null references public.qr_ride_categories(id), status qr_ride_status not null default 'draft', pickup jsonb not null, destination jsonb not null, distance_meters integer, duration_seconds integer, quoted_fare_minor bigint not null check(quoted_fare_minor>=0), final_fare_minor bigint, idempotency_key text not null, pricing_version text not null, requested_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), unique(customer_id,idempotency_key));
create table public.qr_ride_events (id bigint generated always as identity primary key, ride_id uuid not null references public.qr_rides(id) on delete cascade, actor_id uuid references public.qr_profiles(id), event_type text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.qr_negotiation_offers (id uuid primary key default gen_random_uuid(), ride_id uuid not null references public.qr_rides(id) on delete cascade, proposer_id uuid not null references public.qr_profiles(id), amount_minor bigint not null check(amount_minor>0), status text not null check(status in ('pending','accepted','rejected','expired','superseded')), expires_at timestamptz not null, created_at timestamptz not null default now());
create table public.qr_wallets (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.qr_profiles(id), owner_type qr_wallet_owner not null, currency char(3) not null, available_minor bigint not null default 0, pending_minor bigint not null default 0, unique(owner_id,owner_type,currency));
create table public.qr_ledger_entries (id uuid primary key default gen_random_uuid(), wallet_id uuid not null references public.qr_wallets(id), ride_id uuid references public.qr_rides(id), kind qr_ledger_kind not null, amount_minor bigint not null check(amount_minor<>0), currency char(3) not null, idempotency_key text not null unique, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.qr_payment_attempts (id uuid primary key default gen_random_uuid(), ride_id uuid not null references public.qr_rides(id), provider text not null, provider_reference text unique, amount_minor bigint not null, currency char(3) not null, state text not null check(state in ('created','authorized','captured','failed','reversed','refunded','disputed')), raw_event jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.qr_token_ledger (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.qr_profiles(id), ride_id uuid unique references public.qr_rides(id), amount integer not null, reason text not null, idempotency_key text unique not null, created_at timestamptz not null default now());
create table public.qr_configuration_versions (id uuid primary key default gen_random_uuid(), key text not null, scope jsonb not null default '{}'::jsonb, value jsonb not null, effective_from timestamptz not null, effective_to timestamptz, created_by uuid references public.qr_profiles(id), approved_by uuid references public.qr_profiles(id), created_at timestamptz not null default now());
create index qr_rides_dispatch_idx on public.qr_rides(city_id, status, created_at desc); create index qr_ledger_wallet_idx on public.qr_ledger_entries(wallet_id,created_at desc); create index qr_events_ride_idx on public.qr_ride_events(ride_id,created_at);

alter table public.qr_profiles enable row level security; alter table public.qr_drivers enable row level security; alter table public.qr_rides enable row level security; alter table public.qr_ride_events enable row level security; alter table public.qr_wallets enable row level security; alter table public.qr_ledger_entries enable row level security; alter table public.qr_token_ledger enable row level security;
create function public.qr_is_staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from qr_profiles where id=auth.uid() and role in ('super_admin','operations_admin','finance_admin','support_agent')) $$;
create policy "profiles self or staff" on public.qr_profiles for select to authenticated using (id=auth.uid() or qr_is_staff());
create policy "rides participant or staff" on public.qr_rides for select to authenticated using (customer_id=auth.uid() or driver_id=auth.uid() or qr_is_staff());
create policy "ride events participant or staff" on public.qr_ride_events for select to authenticated using (exists(select 1 from qr_rides r where r.id=ride_id and (r.customer_id=auth.uid() or r.driver_id=auth.uid() or qr_is_staff())));
create policy "wallet owner or staff" on public.qr_wallets for select to authenticated using (owner_id=auth.uid() or qr_is_staff());
create policy "ledger owner or finance" on public.qr_ledger_entries for select to authenticated using (exists(select 1 from qr_wallets w where w.id=wallet_id and (w.owner_id=auth.uid() or qr_is_staff())));
create policy "tokens owner or staff" on public.qr_token_ledger for select to authenticated using (customer_id=auth.uid() or qr_is_staff());

-- Append-only protection. Settlement worker uses a service role / trusted function.
create function public.qr_reject_ledger_mutation() returns trigger language plpgsql as $$ begin raise exception 'Ledger entries are immutable'; end $$;
create trigger qr_ledger_immutable before update or delete on public.qr_ledger_entries for each row execute function public.qr_reject_ledger_mutation();
create trigger qr_token_immutable before update or delete on public.qr_token_ledger for each row execute function public.qr_reject_ledger_mutation();
